<?php

// CLI entry point. Usage: php console.php route:cache | route:clear

require_once __DIR__ . '/core/autoload.php';
require_once __DIR__ . '/core/route.php';

$cacheFile = __DIR__ . '/bootstrap/cache/routes.php';
$command = $argv[1] ?? null;

switch ($command) {
    case 'route:cache':
        require __DIR__ . '/routes/web.php';

        foreach ($routes as $items) {
            foreach ($items as $item) {
                if (!is_string($item['action'])) {
                    fwrite(STDERR, "Cannot cache a closure route — use 'Controller@method' action strings only.\n");
                    exit(1);
                }
            }
        }

        if (!is_dir(dirname($cacheFile))) {
            mkdir(dirname($cacheFile), 0755, true);
        }

        file_put_contents(
            $cacheFile,
            "<?php\n\n// Generated by `php console.php route:cache`. Do not edit by hand.\nreturn " . var_export($routes, true) . ";\n"
        );

        echo "Routes cached to bootstrap/cache/routes.php\n";
        break;

    case 'route:clear':
        if (file_exists($cacheFile)) {
            unlink($cacheFile);
            echo "Route cache cleared.\n";
        } else {
            echo "No route cache to clear.\n";
        }
        break;

    default:
        echo "Usage: php console.php route:cache|route:clear\n";
}
