<?php

// Signed URLs: a `signature` query parameter (HMAC-SHA256 with APP_KEY over
// the whole URL) that proves the link was generated by this app and was not
// altered — for unsubscribe links, email verification, download links, ...
// An optional `expires` timestamp is part of the signed data. The 'signed'
// middleware aborts 403 when the signature is missing, wrong or expired.

// Scheme and host of the app ("https://example.com"), without the base path.
function app_origin(): string
{
    $url = app_url();
    $scheme = parse_url($url, PHP_URL_SCHEME) ?: 'http';
    $host = parse_url($url, PHP_URL_HOST) ?: 'localhost';
    $port = parse_url($url, PHP_URL_PORT);

    return $scheme . '://' . $host . ($port ? ':' . $port : '');
}

function url_signature(string $url): string
{
    return hash_hmac('sha256', $url, (string) config('app.key', ''));
}

// signed_path('unsubscribe', ['user' => 5], 3600) → "/unsubscribe/5?expires=...&signature=..."
function signed_path(string $routeName, array $params = [], ?int $expiresInSeconds = null): string
{
    return substr(signed_url($routeName, $params, $expiresInSeconds), strlen(app_origin()));
}

function signed_url(string $routeName, array $params = [], ?int $expiresInSeconds = null): string
{
    unset($params['signature']);

    if ($expiresInSeconds !== null) {
        $params['expires'] = time() + $expiresInSeconds;
    }

    $url = app_origin() . route_url($routeName, $params);

    return $url . (str_contains($url, '?') ? '&' : '?') . 'signature=' . url_signature($url);
}

// Temporary link: signed_url_temporary('download', ['file' => 3], 600).
function signed_url_temporary(string $routeName, array $params, int $expiresInSeconds): string
{
    return signed_url($routeName, $params, $expiresInSeconds);
}

// Verifies any absolute URL carrying ?signature=...; the current request's
// URL by default.
function signed_url_valid(?string $url = null): bool
{
    $url ??= request_url();
    $query = (string) parse_url($url, PHP_URL_QUERY);

    parse_str($query, $params);

    $signature = $params['signature'] ?? null;

    if (!is_string($signature) || $signature === '') {
        return false;
    }

    // Strip only the signature parameter, keeping the rest byte-for-byte so
    // the HMAC is computed over exactly what was signed.
    $original = preg_replace('/([?&])signature=[^&]*&/', '$1', $url);
    $original = preg_replace('/[?&]signature=[^&]*$/', '', (string) $original);

    if (!hash_equals(url_signature((string) $original), $signature)) {
        return false;
    }

    $expires = $params['expires'] ?? null;

    if ($expires !== null && (!ctype_digit((string) $expires) || (int) $expires < time())) {
        return false;
    }

    return true;
}

middleware('signed', function (callable $next) {
    if (!signed_url_valid()) {
        abort(403, 'This link is invalid or has expired.');
    }

    return $next();
});
